name: Core Stack

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  booting:
    runs-on: ubuntu-26.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setting Up User
        run: bash user.sh

      - name: Update and Upgrade Packages
        run: bash update.sh

      #- name: Installing Desktop GNOME
      #  run: bash desktop.sh

      - name: Install and Setup ngrok SSH tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          sudo snap install ngrok

          mkdir -p ~/.config/ngrok

          ngrok config add-authtoken "$NGROK_AUTH_TOKEN"

          nohup ngrok tcp 22 > ngrok.log 2>&1 &

          sleep 5

          cat ngrok.log

      - name: Holder
        run: sleep 86400
